#!/bin/sh /etc/rc.common
# Start script for linux-NFC tool neard
# Copyright (C) 2007 OpenWrt.org

START=97

APP=`which neard`

SERVICE_DAEMONIZE=1

start() {

        service_start $APP
}

stop() {
        service_stop $APP
}

